// <auto-generated />
using System;
using ExpressVoituresDotNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpressVoituresDotNet.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251009211929_UpdateApplicationDbContext")]
    partial class UpdateApplicationDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RepairCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("Repairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Repair description 1",
                            RepairCost = 500.00m,
                            RepairDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Repair description 2",
                            RepairCost = 700.00m,
                            RepairDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "Repair description 3",
                            RepairCost = 600.00m,
                            RepairDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 4,
                            Description = "Repair description 4",
                            RepairCost = 800.00m,
                            RepairDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 5
                        },
                        new
                        {
                            Id = 5,
                            Description = "Repair description 5",
                            RepairCost = 900.00m,
                            RepairDate = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 6
                        },
                        new
                        {
                            Id = 6,
                            Description = "Repair description 6",
                            RepairCost = 1000.00m,
                            RepairDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 7
                        },
                        new
                        {
                            Id = 7,
                            Description = "Repair description 7",
                            RepairCost = 1100.00m,
                            RepairDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 8
                        },
                        new
                        {
                            Id = 8,
                            Description = "Repair description 8",
                            RepairCost = 1200.00m,
                            RepairDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 10
                        });
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Purchase")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Sale")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleBrandId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleTrimId")
                        .HasColumnType("int");

                    b.Property<int>("YearOfProduction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleBrandId");

                    b.HasIndex("VehicleModelId");

                    b.HasIndex("VehicleTrimId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Vehicle description 1",
                            Label = "Vehicle 1",
                            MediaLabel = "CE.png",
                            MediaPath = "/images/vehicles/CE.png",
                            Purchase = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 15000m,
                            Status = 1,
                            VIN = "1HGCM82633A123001",
                            VehicleBrandId = 1,
                            VehicleModelId = 1,
                            VehicleTrimId = 1,
                            YearOfProduction = 2020
                        },
                        new
                        {
                            Id = 2,
                            Description = "Vehicle description 2",
                            Label = "Vehicle 2",
                            MediaLabel = "CE.png",
                            MediaPath = "/images/vehicles/CE.png",
                            Purchase = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 18000m,
                            Status = 0,
                            VIN = "1HGCM82633A123002",
                            VehicleBrandId = 2,
                            VehicleModelId = 2,
                            VehicleTrimId = 1,
                            YearOfProduction = 2021
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vehicle description 3",
                            Label = "Vehicle 3",
                            MediaLabel = "CE.png",
                            MediaPath = "/images/vehicles/CE.png",
                            Purchase = new DateTime(2019, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 16000m,
                            Sale = new DateTime(2020, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 16500m,
                            Status = 2,
                            VIN = "1HGCM82633A123003",
                            VehicleBrandId = 3,
                            VehicleModelId = 3,
                            VehicleTrimId = 2,
                            YearOfProduction = 2019
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vehicle description 4",
                            Label = "Vehicle 4",
                            MediaLabel = "CE.png",
                            MediaPath = "/images/vehicles/CE.png",
                            Purchase = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 20000m,
                            Status = 1,
                            VIN = "1HGCM82633A123004",
                            VehicleBrandId = 4,
                            VehicleModelId = 4,
                            VehicleTrimId = 3,
                            YearOfProduction = 2022
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vehicle description 5",
                            Label = "Vehicle 5",
                            MediaLabel = "CE.png",
                            MediaPath = "/images/vehicles/CE.png",
                            Purchase = new DateTime(2018, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 14000m,
                            Sale = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 14500m,
                            Status = 2,
                            VIN = "1HGCM82633A123005",
                            VehicleBrandId = 5,
                            VehicleModelId = 5,
                            VehicleTrimId = 4,
                            YearOfProduction = 2018
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vehicle description 6",
                            Label = "Vehicle 6",
                            MediaLabel = "CE.png",
                            MediaPath = "/images/vehicles/CE.png",
                            Purchase = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 22000m,
                            Status = 1,
                            VIN = "1HGCM82633A123006",
                            VehicleBrandId = 6,
                            VehicleModelId = 6,
                            VehicleTrimId = 5,
                            YearOfProduction = 2021
                        },
                        new
                        {
                            Id = 7,
                            Description = "Vehicle description 7",
                            Label = "Vehicle 7",
                            MediaLabel = "CE.png",
                            MediaPath = "/images/vehicles/CE.png",
                            Purchase = new DateTime(2020, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 13000m,
                            Status = 1,
                            VIN = "1HGCM82633A123007",
                            VehicleBrandId = 7,
                            VehicleModelId = 7,
                            VehicleTrimId = 6,
                            YearOfProduction = 2020
                        },
                        new
                        {
                            Id = 8,
                            Description = "Vehicle description 8",
                            Label = "Vehicle 8",
                            MediaLabel = "CE.png",
                            MediaPath = "/images/vehicles/CE.png",
                            Purchase = new DateTime(2019, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 15500m,
                            Sale = new DateTime(2020, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 16000m,
                            Status = 2,
                            VIN = "1HGCM82633A123008",
                            VehicleBrandId = 8,
                            VehicleModelId = 8,
                            VehicleTrimId = 7,
                            YearOfProduction = 2019
                        },
                        new
                        {
                            Id = 9,
                            Description = "Vehicle description 9",
                            Label = "Vehicle 9",
                            MediaLabel = "CE.png",
                            MediaPath = "/images/vehicles/CE.png",
                            Purchase = new DateTime(2022, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 17500m,
                            Status = 0,
                            VIN = "1HGCM82633A123009",
                            VehicleBrandId = 9,
                            VehicleModelId = 9,
                            VehicleTrimId = 8,
                            YearOfProduction = 2022
                        },
                        new
                        {
                            Id = 10,
                            Description = "Vehicle description 10",
                            Label = "Vehicle 10",
                            MediaLabel = "CE.png",
                            MediaPath = "/images/vehicles/CE.png",
                            Purchase = new DateTime(2021, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 19000m,
                            Status = 1,
                            VIN = "1HGCM82633A123010",
                            VehicleBrandId = 10,
                            VehicleModelId = 10,
                            VehicleTrimId = 9,
                            YearOfProduction = 2021
                        });
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.VehicleBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Honda"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Chevrolet"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Nissan"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Volkswagen"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Renault"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Peugeot"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Citroën"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Jeep"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Mazda"
                        });
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.VehicleBrandModel", b =>
                {
                    b.Property<int>("VehicleBrandId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.HasKey("VehicleBrandId", "VehicleModelId");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("VehicleBrandModels");

                    b.HasData(
                        new
                        {
                            VehicleBrandId = 1,
                            VehicleModelId = 1
                        },
                        new
                        {
                            VehicleBrandId = 2,
                            VehicleModelId = 2
                        },
                        new
                        {
                            VehicleBrandId = 3,
                            VehicleModelId = 3
                        },
                        new
                        {
                            VehicleBrandId = 4,
                            VehicleModelId = 4
                        },
                        new
                        {
                            VehicleBrandId = 5,
                            VehicleModelId = 5
                        },
                        new
                        {
                            VehicleBrandId = 6,
                            VehicleModelId = 6
                        },
                        new
                        {
                            VehicleBrandId = 7,
                            VehicleModelId = 7
                        },
                        new
                        {
                            VehicleBrandId = 8,
                            VehicleModelId = 8
                        },
                        new
                        {
                            VehicleBrandId = 9,
                            VehicleModelId = 9
                        },
                        new
                        {
                            VehicleBrandId = 10,
                            VehicleModelId = 10
                        },
                        new
                        {
                            VehicleBrandId = 11,
                            VehicleModelId = 11
                        });
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            Model = "Focus"
                        },
                        new
                        {
                            Id = 3,
                            Model = "Civic"
                        },
                        new
                        {
                            Id = 4,
                            Model = "Impala"
                        },
                        new
                        {
                            Id = 5,
                            Model = "Altima"
                        },
                        new
                        {
                            Id = 6,
                            Model = "Golf"
                        },
                        new
                        {
                            Id = 7,
                            Model = "Clio"
                        },
                        new
                        {
                            Id = 8,
                            Model = "208"
                        },
                        new
                        {
                            Id = 9,
                            Model = "C3"
                        },
                        new
                        {
                            Id = 10,
                            Model = "Wrangler"
                        },
                        new
                        {
                            Id = 11,
                            Model = "CX-5"
                        });
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.VehicleModelVehicleTrim", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleTrimId")
                        .HasColumnType("int");

                    b.HasKey("VehicleModelId", "VehicleTrimId");

                    b.HasIndex("VehicleTrimId");

                    b.ToTable("VehicleModelVehicleTrims");

                    b.HasData(
                        new
                        {
                            VehicleModelId = 1,
                            VehicleTrimId = 1
                        },
                        new
                        {
                            VehicleModelId = 1,
                            VehicleTrimId = 2
                        },
                        new
                        {
                            VehicleModelId = 2,
                            VehicleTrimId = 1
                        },
                        new
                        {
                            VehicleModelId = 2,
                            VehicleTrimId = 3
                        },
                        new
                        {
                            VehicleModelId = 3,
                            VehicleTrimId = 2
                        },
                        new
                        {
                            VehicleModelId = 3,
                            VehicleTrimId = 4
                        },
                        new
                        {
                            VehicleModelId = 4,
                            VehicleTrimId = 3
                        },
                        new
                        {
                            VehicleModelId = 4,
                            VehicleTrimId = 5
                        },
                        new
                        {
                            VehicleModelId = 5,
                            VehicleTrimId = 4
                        });
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.VehicleTrim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TrimLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleTrims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TrimLabel = "Base"
                        },
                        new
                        {
                            Id = 2,
                            TrimLabel = "SE"
                        },
                        new
                        {
                            Id = 3,
                            TrimLabel = "LE"
                        },
                        new
                        {
                            Id = 4,
                            TrimLabel = "S"
                        },
                        new
                        {
                            Id = 5,
                            TrimLabel = "SE"
                        },
                        new
                        {
                            Id = 6,
                            TrimLabel = "Titanium"
                        },
                        new
                        {
                            Id = 7,
                            TrimLabel = "LX"
                        },
                        new
                        {
                            Id = 8,
                            TrimLabel = "EX"
                        },
                        new
                        {
                            Id = 9,
                            TrimLabel = "Touring"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.Repair", b =>
                {
                    b.HasOne("ExpressVoituresDotNet.Models.Entities.Vehicle", "Vehicle")
                        .WithOne("Repair")
                        .HasForeignKey("ExpressVoituresDotNet.Models.Entities.Repair", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.Vehicle", b =>
                {
                    b.HasOne("ExpressVoituresDotNet.Models.Entities.VehicleBrand", "VehicleBrand")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpressVoituresDotNet.Models.Entities.VehicleModel", "VehicleModel")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpressVoituresDotNet.Models.Entities.VehicleTrim", "VehicleTrim")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTrimId");

                    b.Navigation("VehicleBrand");

                    b.Navigation("VehicleModel");

                    b.Navigation("VehicleTrim");
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.VehicleBrandModel", b =>
                {
                    b.HasOne("ExpressVoituresDotNet.Models.Entities.VehicleBrand", "VehicleBrand")
                        .WithMany("VehicleBrandModels")
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpressVoituresDotNet.Models.Entities.VehicleModel", "VehicleModel")
                        .WithMany("VehicleBrandModels")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleBrand");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.VehicleModelVehicleTrim", b =>
                {
                    b.HasOne("ExpressVoituresDotNet.Models.Entities.VehicleModel", "VehicleModel")
                        .WithMany("VehicleModelVehicleTrims")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpressVoituresDotNet.Models.Entities.VehicleTrim", "VehicleTrim")
                        .WithMany("VehicleModelVehicleTrims")
                        .HasForeignKey("VehicleTrimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleModel");

                    b.Navigation("VehicleTrim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.Vehicle", b =>
                {
                    b.Navigation("Repair");
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.VehicleBrand", b =>
                {
                    b.Navigation("VehicleBrandModels");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.VehicleModel", b =>
                {
                    b.Navigation("VehicleBrandModels");

                    b.Navigation("VehicleModelVehicleTrims");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ExpressVoituresDotNet.Models.Entities.VehicleTrim", b =>
                {
                    b.Navigation("VehicleModelVehicleTrims");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
